export const Passions = {
    DRAG: "DRAG",
    RALLY: "RALLY",
    DRIFT: "DRIFT",
    NASCAR: "NASCAR",
    FORMULA_1: "FORMULA_1",
    FORMULA_E: "FORMULA_E",
    INDYCAR: "INDYCAR",
    TOURING_CAR: "TOURING_CAR",
    GT: "GT",
    ENDURANCE: "ENDURANCE",
    OFFROAD: "OFFROAD",
    HILL_CLIMB: "HILL_CLIMB",
    TIME_ATTACK: "TIME_ATTACK",
    AUTOCROSS: "AUTOCROSS",
    RALLYCROSS: "RALLYCROSS",
    SPRINT: "SPRINT",
    STOCK_CAR: "STOCK_CAR",
    FORMULA_DRIFT: "FORMULA_DRIFT",
    TRUCK_RACING: "TRUCK_RACING",
    FORMULA_STUDENT: "FORMULA_STUDENT",
    LANDSPEED_RECORD: "LANDSPEED_RECORD",
    RALLY_RAID: "RALLY_RAID",
    DIRT_TRACK: "DIRT_TRACK"
} as const;

export type Passions = typeof Passions[keyof typeof Passions];
